name: myapp2
description: A new Flutter project.

publish_to:

version: 1.0.0+1

environment:
  sdk: '>=2.18.5 <3.0.0'


dependencies:
  flutter:
    sdk: flutter
  rive: ^0.10.3


  cupertino_icons: ^1.0.2
  google_nav_bar: ^5.0.6
  animated_splash_screen: ^1.1.8
  cloud_firestore: ^4.3.0
  firebase_storage: ^11.0.14
  firebase_auth: ^4.4.1
  firebase_admin:
  firebase_core: ^2.4.0
  flutter_spinkit: ^5.1.0
  carousel_slider: ^4.2.1
  shimmer: ^2.0.0
  color: ^3.0.0
  random_password_generator: ^0.2.1
  flutter_local_notifications: ^13.0.0
  #image_cropper: ^3.0.1
  image_picker: ^0.8.6
  path_provider: ^2.0.11
  http: ^0.13.5
  flutter_image_compress: ^1.1.3
  dropdown_textfield: ^1.0.7
  date_time_format: ^2.0.1
  flutter_linkify: ^5.0.2
  font_awesome_flutter: ^10.3.0
  path: ^1.6.4
  flutter_file_manager: ^0.2.0
  url_launcher: ^6.1.10
#  table_calendar: ^3.0.9
#  photofilters: ^3.0.1
  shared_preferences: ^2.1.0
  flutter_cache_manager: ^3.3.0
  firebase_database: ^10.0.16
  file_picker: ^5.2.6
  open_filex: ^4.3.2
  google_fonts: ^4.0.3



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.12.0

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/vsitr-logo.jpg"

  flutter_lints: ^2.0.0


flutter:


  uses-material-design: true

  assets:
    - assets/images/


