// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCV7qGe5KNqHKCpVeyf-WWhLg9gnBtFuqA',
    appId: '1:466322679407:web:d589161cc9ba7e91c98f9a',
    messagingSenderId: '466322679407',
    projectId: 'flutter-classroom-48dd1',
    authDomain: 'flutter-classroom-48dd1.firebaseapp.com',
    databaseURL: "https://flutter-classroom-48dd1-default-rtdb.firebaseio.com",
    storageBucket: 'flutter-classroom-48dd1.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA7a5xJidUFV5PcavOMVYjZZi5z-t-MLsM',
    appId: '1:466322679407:android:8e62aee614f21218c98f9a',
    messagingSenderId: '466322679407',
    projectId: 'flutter-classroom-48dd1',
    storageBucket: 'flutter-classroom-48dd1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCoPXJdEsQ_Ct2jbvd1OwaSAjOa2bHVn-8',
    appId: '1:466322679407:ios:2abb1db6e8c3b1b1c98f9a',
    messagingSenderId: '466322679407',
    projectId: 'flutter-classroom-48dd1',
    storageBucket: 'flutter-classroom-48dd1.appspot.com',
    iosClientId:
        '466322679407-v4nupe5uqrs31r2269h9v6m9o5tse6bb.apps.googleusercontent.com',
    iosBundleId: 'com.example.myapp2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCoPXJdEsQ_Ct2jbvd1OwaSAjOa2bHVn-8',
    appId: '1:466322679407:ios:2abb1db6e8c3b1b1c98f9a',
    messagingSenderId: '466322679407',
    projectId: 'flutter-classroom-48dd1',
    storageBucket: 'flutter-classroom-48dd1.appspot.com',
    iosClientId: '466322679407-v4nupe5uqrs31r2269h9v6m9o5tse6bb.apps.googleusercontent.com',
    iosBundleId: 'com.example.myapp2',
  );
}
